### ISSUE TITLE
no .sql file

### ISSUE THREAD

**Issue by thanksGitHub** [prabb/wiki#1]
hello Prabhdeep,I fork this project,but meet some problem,for example no .sql file to create database;

**Comment by prabh-62** [comment]
Hey @thanksGithub,  we actually don't require any sql file to generate the database schema. It automatically gets created.

All we need to do is to make sure the application is able to connect to mySQL database. Edit the file in `src/main/resources/hibernate.cfg.xml` to make sure MySQL database can be reached.

**Comment by thanksGitHub** [comment]
I`m so happy you give the information,so I found the really reason.the mysql-connect -6-XX jar is to high,and i`m not used hibenate , now the issus is solve，thanks once again.
